-- GENERATED by content/seed.mjs from content/exercises.yaml. Do not edit.
BEGIN TRANSACTION;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l0-sustained-s', 0, 's', 'isolation', 'ssss', NULL, NULL, '["warmup"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-sah', 1, 's', 'initial', 'sah', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-say', 1, 's', 'initial', 'say', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-see', 1, 's', 'initial', 'see', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-sigh', 1, 's', 'initial', 'sigh', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-so', 1, 's', 'initial', 'so', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-sue', 1, 's', 'initial', 'sue', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-saw', 1, 's', 'initial', 'saw', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-suh', 1, 's', 'initial', 'suh', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-seh', 1, 's', 'initial', 'seh', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-sih', 1, 's', 'initial', 'sih', NULL, NULL, '["cv"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-as', 1, 's', 'final', 'as', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-ess', 1, 's', 'final', 'ess', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-iss', 1, 's', 'final', 'iss', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-oss', 1, 's', 'final', 'oss', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-uss', 1, 's', 'final', 'uss', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-ace', 1, 's', 'final', 'ace', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-ice', 1, 's', 'final', 'ice', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-oos', 1, 's', 'final', 'oos', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-aws', 1, 's', 'final', 'aws', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l1-eese', 1, 's', 'final', 'eese', NULL, NULL, '["vc"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-see', 2, 's', 'initial', 'see', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sit', 2, 's', 'initial', 'sit', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-set', 2, 's', 'initial', 'set', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sat', 2, 's', 'initial', 'sat', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sun', 2, 's', 'initial', 'sun', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-soup', 2, 's', 'initial', 'soup', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-saw', 2, 's', 'initial', 'saw', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-so', 2, 's', 'initial', 'so', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sea', 2, 's', 'initial', 'sea', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-said', 2, 's', 'initial', 'said', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sand', 2, 's', 'initial', 'sand', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sock', 2, 's', 'initial', 'sock', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-soap', 2, 's', 'initial', 'soap', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sad', 2, 's', 'initial', 'sad', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sing', 2, 's', 'initial', 'sing', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-six', 2, 's', 'initial', 'six', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-seat', 2, 's', 'initial', 'seat', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sell', 2, 's', 'initial', 'sell', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sick', 2, 's', 'initial', 'sick', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-song', 2, 's', 'initial', 'song', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-suit', 2, 's', 'initial', 'suit', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-safe', 2, 's', 'initial', 'safe', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-same', 2, 's', 'initial', 'same', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-seven', 2, 's', 'initial', 'seven', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-silver', 2, 's', 'initial', 'silver', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-summer', 2, 's', 'initial', 'summer', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-sorry', 2, 's', 'initial', 'sorry', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-simple', 2, 's', 'initial', 'simple', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-second', 2, 's', 'initial', 'second', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-city', 2, 's', 'initial', 'city', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zoo', 2, 'z', 'initial', 'zoo', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zip', 2, 'z', 'initial', 'zip', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zero', 2, 'z', 'initial', 'zero', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zebra', 2, 'z', 'initial', 'zebra', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zone', 2, 'z', 'initial', 'zone', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zoom', 2, 'z', 'initial', 'zoom', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zigzag', 2, 'z', 'initial', 'zigzag', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zest', 2, 'z', 'initial', 'zest', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zinc', 2, 'z', 'initial', 'zinc', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l2-zap', 2, 'z', 'initial', 'zap', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-bus', 3, 's', 'final', 'bus', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-yes', 3, 's', 'final', 'yes', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-house', 3, 's', 'final', 'house', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-gas', 3, 's', 'final', 'gas', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-kiss', 3, 's', 'final', 'kiss', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-miss', 3, 's', 'final', 'miss', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-this', 3, 's', 'final', 'this', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-class', 3, 's', 'final', 'class', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-glass', 3, 's', 'final', 'glass', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-grass', 3, 's', 'final', 'grass', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-pass', 3, 's', 'final', 'pass', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-less', 3, 's', 'final', 'less', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-mess', 3, 's', 'final', 'mess', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-dress', 3, 's', 'final', 'dress', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-price', 3, 's', 'final', 'price', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-nice', 3, 's', 'final', 'nice', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-ice', 3, 's', 'final', 'ice', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-race', 3, 's', 'final', 'race', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-face', 3, 's', 'final', 'face', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-place', 3, 's', 'final', 'place', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-space', 3, 's', 'final', 'space', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-juice', 3, 's', 'final', 'juice', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-mouse', 3, 's', 'final', 'mouse', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-horse', 3, 's', 'final', 'horse', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-purse', 3, 's', 'final', 'purse', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-nurse', 3, 's', 'final', 'nurse', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-piece', 3, 's', 'final', 'piece', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-peace', 3, 's', 'final', 'peace', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-voice', 3, 's', 'final', 'voice', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-choice', 3, 's', 'final', 'choice', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-buzz', 3, 'z', 'final', 'buzz', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-jazz', 3, 'z', 'final', 'jazz', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-nose', 3, 'z', 'final', 'nose', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-rose', 3, 'z', 'final', 'rose', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-size', 3, 'z', 'final', 'size', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-prize', 3, 'z', 'final', 'prize', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-cheese', 3, 'z', 'final', 'cheese', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l3-please', 3, 'z', 'final', 'please', NULL, NULL, '["word","voiced-twin"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-basket', 4, 's', 'medial', 'basket', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-missing', 4, 's', 'medial', 'missing', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-lesson', 4, 's', 'medial', 'lesson', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-listen', 4, 's', 'medial', 'listen', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-whisper', 4, 's', 'medial', 'whisper', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-castle', 4, 's', 'medial', 'castle', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-pencil', 4, 's', 'medial', 'pencil', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-answer', 4, 's', 'medial', 'answer', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-bicycle', 4, 's', 'medial', 'bicycle', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-eraser', 4, 's', 'medial', 'eraser', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-dinosaur', 4, 's', 'medial', 'dinosaur', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-exercise', 4, 's', 'medial', 'exercise', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-messenger', 4, 's', 'medial', 'messenger', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-muscle', 4, 's', 'medial', 'muscle', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-recipe', 4, 's', 'medial', 'recipe', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-medicine', 4, 's', 'medial', 'medicine', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-hospital', 4, 's', 'medial', 'hospital', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-password', 4, 's', 'medial', 'password', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-crossing', 4, 's', 'medial', 'crossing', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-glasses', 4, 's', 'medial', 'glasses', NULL, NULL, '["word"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-stop', 4, 's', 'cluster', 'stop', NULL, NULL, '["cluster","st-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-star', 4, 's', 'cluster', 'star', NULL, NULL, '["cluster","st-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-stand', 4, 's', 'cluster', 'stand', NULL, NULL, '["cluster","st-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-story', 4, 's', 'cluster', 'story', NULL, NULL, '["cluster","st-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-steam', 4, 's', 'cluster', 'steam', NULL, NULL, '["cluster","st-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-street', 4, 's', 'cluster', 'street', NULL, NULL, '["cluster","st-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-spoon', 4, 's', 'cluster', 'spoon', NULL, NULL, '["cluster","sp-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-spider', 4, 's', 'cluster', 'spider', NULL, NULL, '["cluster","sp-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-spell', 4, 's', 'cluster', 'spell', NULL, NULL, '["cluster","sp-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-speak', 4, 's', 'cluster', 'speak', NULL, NULL, '["cluster","sp-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-sky', 4, 's', 'cluster', 'sky', NULL, NULL, '["cluster","sk-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-skate', 4, 's', 'cluster', 'skate', NULL, NULL, '["cluster","sk-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-school', 4, 's', 'cluster', 'school', NULL, NULL, '["cluster","sk-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-skip', 4, 's', 'cluster', 'skip', NULL, NULL, '["cluster","sk-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-sleep', 4, 's', 'cluster', 'sleep', NULL, NULL, '["cluster","sl-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-slow', 4, 's', 'cluster', 'slow', NULL, NULL, '["cluster","sl-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-slide', 4, 's', 'cluster', 'slide', NULL, NULL, '["cluster","sl-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-slip', 4, 's', 'cluster', 'slip', NULL, NULL, '["cluster","sl-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-smile', 4, 's', 'cluster', 'smile', NULL, NULL, '["cluster","sm-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-small', 4, 's', 'cluster', 'small', NULL, NULL, '["cluster","sm-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-smoke', 4, 's', 'cluster', 'smoke', NULL, NULL, '["cluster","sm-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-smart', 4, 's', 'cluster', 'smart', NULL, NULL, '["cluster","sm-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-snow', 4, 's', 'cluster', 'snow', NULL, NULL, '["cluster","sn-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-snake', 4, 's', 'cluster', 'snake', NULL, NULL, '["cluster","sn-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-snack', 4, 's', 'cluster', 'snack', NULL, NULL, '["cluster","sn-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-sneeze', 4, 's', 'cluster', 'sneeze', NULL, NULL, '["cluster","sn-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-swim', 4, 's', 'cluster', 'swim', NULL, NULL, '["cluster","sw-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-sweet', 4, 's', 'cluster', 'sweet', NULL, NULL, '["cluster","sw-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-swing', 4, 's', 'cluster', 'swing', NULL, NULL, '["cluster","sw-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l4-sweater', 4, 's', 'cluster', 'sweater', NULL, NULL, '["cluster","sw-"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-see-you-soon', 5, 's', 'phrase', 'see you soon', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-sit-down-please', 5, 's', 'phrase', 'sit down please', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-a-sunny-sunday', 5, 's', 'phrase', 'a sunny Sunday', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-seven-small-seats', 5, 's', 'phrase', 'seven small seats', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-pass-the-salt', 5, 's', 'phrase', 'pass the salt', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-sorry-to-miss-it', 5, 's', 'phrase', 'sorry to miss it', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-this-side-up', 5, 's', 'phrase', 'this side up', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-nice-and-simple', 5, 's', 'phrase', 'nice and simple', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-same-as-last-time', 5, 's', 'phrase', 'same as last time', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-a-glass-of-juice', 5, 's', 'phrase', 'a glass of juice', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-slow-down-a-second', 5, 's', 'phrase', 'slow down a second', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-the-answer-is-yes', 5, 's', 'phrase', 'the answer is yes', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-send-it-across', 5, 's', 'phrase', 'send it across', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-sales-and-solutions', 5, 's', 'phrase', 'sales and solutions', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-just-a-second', 5, 's', 'phrase', 'just a second', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-let-us-discuss-it', 5, 's', 'phrase', 'let us discuss it', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-sounds-sensible', 5, 's', 'phrase', 'sounds sensible', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-six-or-seven-steps', 5, 's', 'phrase', 'six or seven steps', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-space-for-us', 5, 's', 'phrase', 'space for us', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-close-the-case', 5, 's', 'phrase', 'close the case', NULL, NULL, '["phrase"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-sink-think', 5, 's', 'phrase', 'sink', 'think', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-sum-thumb', 5, 's', 'phrase', 'sum', 'thumb', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-sick-thick', 5, 's', 'phrase', 'sick', 'thick', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-mouse-mouth', 5, 's', 'phrase', 'mouse', 'mouth', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-face-faith', 5, 's', 'phrase', 'face', 'faith', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-pass-path', 5, 's', 'phrase', 'pass', 'path', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-seem-theme', 5, 's', 'phrase', 'seem', 'theme', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-sing-thing', 5, 's', 'phrase', 'sing', 'thing', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-saw-thaw', 5, 's', 'phrase', 'saw', 'thaw', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-sought-thought', 5, 's', 'phrase', 'sought', 'thought', NULL, '["minimal-pair","s-th"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-sip-ship', 5, 's', 'phrase', 'sip', 'ship', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-sue-shoe', 5, 's', 'phrase', 'sue', 'shoe', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-sock-shock', 5, 's', 'phrase', 'sock', 'shock', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-seat-sheet', 5, 's', 'phrase', 'seat', 'sheet', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-mass-mash', 5, 's', 'phrase', 'mass', 'mash', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-class-clash', 5, 's', 'phrase', 'class', 'clash', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-said-shed', 5, 's', 'phrase', 'said', 'shed', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-sell-shell', 5, 's', 'phrase', 'sell', 'shell', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-save-shave', 5, 's', 'phrase', 'save', 'shave', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l5-mp-so-show', 5, 's', 'phrase', 'so', 'show', NULL, '["minimal-pair","s-sh"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-01', 6, 's', 'sentence', 'Sales solutions start with simple conversations.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-02', 6, 's', 'sentence', 'The security process is simpler this season.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-03', 6, 's', 'sentence', 'Six customers signed subscriptions last Saturday.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-04', 6, 's', 'sentence', 'Salesforce sends us a summary after every session.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-05', 6, 's', 'sentence', 'Cisco systems support seventeen separate sites.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-06', 6, 's', 'sentence', 'Singapore and Indonesia are our strongest markets.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-07', 6, 's', 'sentence', 'She said the proposal seems sensible.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-08', 6, 's', 'sentence', 'Please send the spreadsheet across this morning.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-09', 6, 's', 'sentence', 'Success depends on consistent customer service.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-10', 6, 's', 'sentence', 'Some suppliers still insist on separate invoices.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-11', 6, 's', 'sentence', 'Our subscription costs less than last year system.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-12', 6, 's', 'sentence', 'Steve suggested a smaller sample size.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-13', 6, 's', 'sentence', 'The assessment starts at seven sharp.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-14', 6, 's', 'sentence', 'Customers expect fast answers, not excuses.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-15', 6, 's', 'sentence', 'This solution saves us significant space.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-16', 6, 's', 'sentence', 'Sixteen staff sat through the safety session.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-17', 6, 's', 'sentence', 'We discussed prices and services separately.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-18', 6, 's', 'sentence', 'Sam presentation was surprisingly persuasive.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-19', 6, 's', 'sentence', 'The system sends a message as soon as it starts.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-20', 6, 's', 'sentence', 'Sales in Singapore surpassed last season results.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-21', 6, 's', 'sentence', 'Please assess the risks before we sign.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-22', 6, 's', 'sentence', 'Several sites still use the same password.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-23', 6, 's', 'sentence', 'Customer success is a slow, steady process.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-24', 6, 's', 'sentence', 'Susan spoke to seven prospects on Sunday.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-25', 6, 's', 'sentence', 'The software supports seamless synchronisation.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-26', 6, 's', 'sentence', 'Our services scale as the business grows.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-27', 6, 's', 'sentence', 'She sent a summary of the security assessment.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-28', 6, 's', 'sentence', 'Sometimes the simplest answer is the safest.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-29', 6, 's', 'sentence', 'Six sales specialists start next Monday.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l6-sentence-30', 6, 's', 'sentence', 'The customer said the system saves them stress.', NULL, NULL, '["sentence"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l7-rainbow-passage', 7, 's', 'passage', 'When the sunlight strikes raindrops in the air, they act as a prism and form a rainbow. The rainbow is a division of white light into many beautiful colors. These take the shape of a long round arch, with its path high above, and its two ends apparently beyond the horizon. There is, according to legend, a boiling pot of gold at one end. People look, but no one ever finds it. When a man looks for something beyond his reach, his friends say he is looking for the pot of gold at the end of the rainbow.', NULL, NULL, '["passage","standard"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l7-call-script-1', 7, 's', 'passage', 'Good morning, this is your name from your company. Thanks for taking the time to speak with me. I want to spend the first five minutes understanding how your security process works today, and then I will show you exactly where our solution fits.', NULL, NULL, '["passage","work"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l7-call-script-2', 7, 's', 'passage', 'Hi, it is your name calling about the subscription discussion we started last Thursday. I have the pricing summary and a sample implementation schedule, so we can settle the specifics in this session.', NULL, NULL, '["passage","work"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l7-call-script-3', 7, 's', 'passage', 'Thanks for joining, everyone. This session has three parts: a summary of last month results, a discussion of the proposed system, and the next steps. I will stop for questions after each section.', NULL, NULL, '["passage","work"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-01', 8, 's', 'free', 'Describe your day so far, from waking up until now.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-02', 8, 's', 'free', 'Pitch one of your products to someone who has never heard of it.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-03', 8, 's', 'free', 'Explain a process you know well, step by step.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-04', 8, 's', 'free', 'Describe the last problem you solved at work.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-05', 8, 's', 'free', 'Talk about somewhere you have travelled and what surprised you.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-06', 8, 's', 'free', 'Explain what your company sells and who buys it.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-07', 8, 's', 'free', 'Describe your ideal Sunday.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-08', 8, 's', 'free', 'Talk through the last conversation you had with a customer.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-09', 8, 's', 'free', 'Explain something you are learning at the moment.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES ('l8-prompt-10', 8, 's', 'free', 'Describe the city you live in to someone who has never visited.', NULL, NULL, '["free-speech"]')
  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, tags = excluded.tags;
COMMIT;
