/**
 * Emits the SQL that seeds `exercises` into D1 from exercises.yaml (spec §6).
 *
 *   node content/seed.mjs > packages/schema/seed/exercises.sql
 *   pnpm --filter @delisp/api exec wrangler d1 execute delisp \
 *     --file=../../packages/schema/seed/exercises.sql --remote
 *
 * Written as an upsert so re-running it after editing the YAML updates the rows
 * rather than failing, and never orphans a trial that references an exercise.
 */
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const here = dirname(fileURLToPath(import.meta.url));
const doc = parse(readFileSync(resolve(here, 'exercises.yaml'), 'utf8'));
const rows = doc?.exercises ?? [];
if (rows.length === 0) throw new Error('exercises.yaml has no exercises');

const quote = (value) =>
  value === null || value === undefined ? 'NULL' : `'${String(value).replace(/'/g, "''")}'`;

const lines = [
  '-- GENERATED by content/seed.mjs from content/exercises.yaml. Do not edit.',
  'BEGIN TRANSACTION;',
];

for (const row of rows) {
  lines.push(
    'INSERT INTO exercises (id, level, sound, position, text, minimal_pair, model_audio_key, tags) VALUES (' +
      [
        quote(row.id),
        Number(row.level),
        quote(row.sound),
        quote(row.position),
        quote(row.text),
        quote(row.minimal_pair ?? null),
        'NULL',
        quote(JSON.stringify(row.tags ?? [])),
      ].join(', ') +
      ')\n  ON CONFLICT(id) DO UPDATE SET level = excluded.level, sound = excluded.sound, ' +
      'position = excluded.position, text = excluded.text, minimal_pair = excluded.minimal_pair, ' +
      'tags = excluded.tags;',
  );
}

lines.push('COMMIT;');
process.stdout.write(`${lines.join('\n')}\n`);
